{{- if .Values.ingress.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    {{- if .Values.ingress.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- end }}
    {{- if .Values.ingress.issueTemporaryCertificate }}
    cert-manager.io/issue-temporary-certificate: "true"
    {{- end }}
    {{- if .Values.ingress.acme }}
    acme.cert-manager.io/http01-edit-in-place: "true"
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128K"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4 256k"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: {{ .Values.ingress.apiPath }}(.*)
            backend:
              service:
                name: {{ .Values.name }}-api
                port:
                  number: 5000
          - pathType: ImplementationSpecific
            path: {{ .Values.ingress.wmsPath }}(.*)
            backend:
              service:
                name: {{ .Values.name }}-wms
                port:
                  number: 5000
          - pathType: ImplementationSpecific
            path: {{ .Values.ingress.webappPath }}(.*)
            backend:
              service:
                name: {{ .Values.name }}-webapp
                port:
                  number: 80
  ingressClassName: {{ .Values.ingress.ingressclass }}
{{- end }}
