apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128K"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4 256k"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: {{ .Values.ingress.apiPath }}(.*)
            backend:
              service:
                name: {{ .Values.name }}-api
                port:
                  number: 5000
          - pathType: ImplementationSpecific
            path: {{ .Values.ingress.webappPath }}(.*)
            backend:
              service:
                name: {{ .Values.name }}-webapp
                port:
                  number: 80
  ingressClassName: {{ .Values.ingress.ingressclass }}

